CREATE TABLE coffees_DID_DN_DS(
	DID INTEGER NOT NULL,
    DN CHARACTER VARYING NOT NULL,
    DS CHARACTER VARYING NOT NULL,
    PRIMARY KEY (DID)
);

CREATE TABLE coffees_CID_CN_CM(
	CID INTEGER NOT NULL,
    CN CHARACTER VARYING NOT NULL,
    CM CHARACTER VARYING NOT NULL,
    PRIMARY KEY(CID)
);

CREATE TABLE rentals_HZ_HC(
	HZ INTEGER NOT NULL,
    HC CHARACTER VARYING NOT NULL,
);

CREATE TABLE rentals_PID_PN(
	PID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY(PID)
);

CREATE TABLE rentals_HID_HZ_HC (
	HID INTEGER NOT NULL,
    HS CHARACTER VARYING NOT NULL,
    HZ INTEGER NOT NULL,
    HC CHARACTER VARYING NOT NULL,
    PRIMARY KEY(HID, HS, HZ, HC)
);

CREATE TABLE projects_ID_MID_MN(
	ID INTEGER NOT NULL,
    MID INTEGER NOT NULL,
    MN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Projects_PID_PN (
	PID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY(PID)
);

CREATE TABLE Projects_SID_SN (
       SID INTEGER NOT NULL, 
       SN CHARACTER VARYING NOT NULL,
       PRIMARY KEY (SID)
);



