DROP TABLE IF EXISTS Rentals;
DROP TABLE IF EXISTS Coffees;
DROP TABLE IF EXISTS Projects;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Rentals (
       PID INTEGER NOT NULL,
       HID INTEGER NOT NULL, 
       PN CHARACTER VARYING NOT NULL, 
       S INTEGER NOT NULL, 
       HS CHARACTER VARYING NOT NULL,
       HZ INTEGER NOT NULL, 
       HC CHARACTER VARYING NOT NULL,
       PRIMARY KEY (PID, HID)
);

CREATE TABLE Coffees (
       DID INTEGER NOT NULL,
       HID INTEGER NOT NULL, 
       CID INTEGER NOT NULL, 
       DN CHARACTER VARYING NOT NULL, 
       DS CHARACTER VARYING NOT NULL, 
       CN CHARACTER VARYING NOT NULL,
       CM CHARACTER VARYING NOT NULL,
       PRIMARY KEY (DID, HID, CID)
);

CREATE TABLE Projects (
       ID INTEGER NOT NULL,
       PID INTEGER NOT NULL, 
       SID INTEGER NOT NULL, 
       SN CHARACTER VARYING NOT NULL, 
       PN CHARACTER VARYING NOT NULL, 
       MID INTEGER NOT NULL,
       MN CHARACTER VARYING NOT NULL,
       PRIMARY KEY (ID, PID, SID)
);

CREATE TABLE Customers (
       CID INTEGER NOT NULL,
       CN CHARACTER VARYING NOT NULL, 
       CS CHARACTER VARYING NOT NULL, 
       CNr INTEGER NOT NULL,
       CZ INTEGER NOT NULL,
       CC CHARACTER VARYING NOT NULL,
       EID INTEGER NOT NULL,
       PRIMARY KEY (CID)
);
